---
title: "2016 NBA teams map"
author: "Flor Allaert"
date: "8 Feb 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, warning=FALSE}
library(leaflet)
coords <- data.frame(
            lat=c(33.757268, 42.366202, 40.682646, 35.225169, 41.880707, 41.496615, 32.790446, 39.748709, 42.696940, 37.750292, 29.750751, 39.763930, 34.043035, 34.043031, 35.138186, 25.781382, 43.043667, 44.979477, 29.949035, 40.750504, 35.463417, 28.539266, 39.901193, 33.445764, 45.531535, 38.580262, 29.427052, 43.643451, 40.768244, 38.898117),
            lng=c(-84.396325, -71.062146, -73.975335, -80.839224, -87.674197, -81.688080, -96.810307, -105.007710, -83.245632, -122.202974, -95.361993, -86.155389, -118.268086, -118.266273, -90.050388, -80.186872, -87.916825, -93.275965, -90.081853, -73.993407, -97.514935, -81.383763, -75.171937, -112.071168, -122.666714, -121.499622, -98.437403, -79.379088, -111.901098, -77.020816))

icons <- iconList(
    i1 = makeIcon("http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/ATL.svg", 40, 40),
    i2 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/BOS.svg", iconWidth=40, iconHeight=40),
    i3 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/BKN.svg", iconWidth=40, iconHeight=40),
    i4 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/CHA.svg", iconWidth=40, iconHeight=40),
    i5 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/CHI.svg", iconWidth=40, iconHeight=40),
    i6 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/CLE.svg", iconWidth=40, iconHeight=40),
    i7 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/DAL.svg", iconWidth=40, iconHeight=40),
    i8 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/DEN.svg", iconWidth=40, iconHeight=40),
    i9 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/DET.svg", iconWidth=40, iconHeight=40),
    i10 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/GSW.svg", iconWidth=40, iconHeight=40),
    i11 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/HOU.svg", iconWidth=40, iconHeight=40),
    i12 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/IND.svg", iconWidth=40, iconHeight=40),
    i13 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/LAC.svg", iconWidth=40, iconHeight=40),
    i14 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/LAL.svg", iconWidth=40, iconHeight=40),
    i15 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/MEM.svg", iconWidth=40, iconHeight=40),
    i16 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/MIA.svg", iconWidth=40, iconHeight=40),
    i17 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/MIL.svg", iconWidth=40, iconHeight=40),
    i18 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/MIN.svg", iconWidth=40, iconHeight=40),
    i19 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/NOP.svg", iconWidth=40, iconHeight=40),
    i20 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/NYK.svg", iconWidth=40, iconHeight=40),
    i21 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/OKC.svg", iconWidth=40, iconHeight=40),
    i22 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/ORL.svg", iconWidth=40, iconHeight=40),
    i23 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/PHI.svg", iconWidth=40, iconHeight=40),
    i24 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/PHX.svg", iconWidth=40, iconHeight=40),
    i25 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/POR.svg", iconWidth=40, iconHeight=40),
    i26 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/SAC.svg", iconWidth=40, iconHeight=40),
    i27 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/SAS.svg", iconWidth=40, iconHeight=40),
    i28 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/TOR.svg", iconWidth=40, iconHeight=40),
    i29 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/UTA.svg", iconWidth=40, iconHeight=40),
    i30 = makeIcon(
    iconUrl="http://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/WAS.svg", iconWidth=40, iconHeight=40)
)

sites <- c(
    "<a href='http://www.nba.com/hawks/'>Atlanta Hawks</a>",
    "<a href='http://www.nba.com/celtics/'>Boston Celtics</a>",
    "<a href='http://www.nba.com/nets/'>Brooklyn Nets</a>",
    "<a href='http://www.nba.com/hornets'>Charlotte Hornets</a>",
    "<a href='http://www.nba.com/bulls'>Chicago Bulls</a>",
    "<a href='http://www.nba.com/cavaliers/'>Cleveland Cavaliers</a>",
    "<a href='http://www.nba.com/teams/mavericks'>Dallas Mavericks</a>",
    "<a href='http://www.nba.com/nuggets/'>Denver Nuggets</a>",
    "<a href='http://www.nba.com/pistons/'>Detroit Pistons</a>",
    "<a href='http://www.nba.com/warriors/'>Golden State Warriors</a>",
    "<a href='http://www.nba.com/rockets/'>Houston Rockets</a>",
    "<a href='http://www.nba.com/pacers/'>Indiana Pacers</a>",
    "<a href='http://www.nba.com/clippers/'>LA Clippers</a>",
    "<a href='http://www.nba.com/lakers/'>LA Lakers</a>",
    "<a href='http://www.nba.com/grizzlies/'>Memphis Grizzlies</a>",
    "<a href='http://www.nba.com/heat/gamedayhub/20170208-miamil'>Miami Heat</a>",
    "<a href='http://www.nba.com/bucks/'>Milwaukee Bucks</a>",
    "<a href='http://www.nba.com/timberwolves/'>Minnesota Timberwolves</a>",
    "<a href='http://www.nba.com/pelicans/?splash=off'>New Orleans Pelicans</a>",
    "<a href='http://www.nba.com/knicks/'>New York Knicks</a>",
    "<a href='http://www.nba.com/thunder/'>Oklahoma Thunder</a>",
    "<a href='http://www.nba.com/magic/'>Orlando Magic</a>",
    "<a href='http://www.nba.com/sixers'>Philadelphia 76ers</a>",
    "<a href='http://www.nba.com/suns'>Phoenix Suns</a>",
    "<a href='http://www.nba.com/blazers/'>Portland Trail Blazers</a>",
    "<a href='http://www.nba.com/kings/'>Sacramento Kings</a>",
    "<a href='http://www.nba.com/spurs/'>San Antonio Spurs</a>",
    "<a href='http://www.nba.com/raptors/?splash=off'>Toronto Raptors</a>",
    "<a href='http://www.nba.com/jazz/'>Utah Jazz</a>",
    "<a href='http://www.nba.com/wizards/'>Washington Wizzards</a>"
)


coords %>% leaflet() %>% addTiles() %>% addMarkers(icon=icons, popup=sites)
```